# Questão 1.

## Funções

In [1]:
using LinearAlgebra

In [2]:
""" O intuito da função resolve_diagonal é resolver equações Dx = b onde A é uma matriz diagonal NxN, 
X é uma matriz Nx1 e b também é uma matriz Nx1. Logo, a função recebe como entrada a Matriz Diagonal 
Quadrada NXN e o vetor B Nx1, e retorna o vetor x Nx1. """

function resolve_diagonal(D,b) # D é diagonal e b é um vetor  
    tamanho = length(b)        # Pega-se o tamanho tanto do vetor quanto da matriz (pressupõe que são de mesmo tamanho)
    x=zeros(tamanho,1)         # Aloca o vetor x a ser retornado
    for i in 1:tamanho 
        x[i] = b[i]/D[i,i]     # Resolve cada x[i] de acordo com o valor da diagonal e o valor de b de cada linha
    end
    
    return x
end

resolve_diagonal (generic function with 1 method)

In [3]:
function resolve_triangular_superior(T,b) #T é triangular superior
    tamanho = length(b)
    x=zeros(tamanho,1)
    
    i = tamanho
    while (i > 0)
        x[i] = b[i]/T[i,i]
        k = tamanho
        for j in i:(tamanho - 1)
            x[i] -= T[i, k] * x[k]/T[i,i]
            k -= 1
        end
        i -= 1
    end
    return x
end

resolve_triangular_superior (generic function with 1 method)

In [4]:
function resolve_triangular_inferior(T,b) #T é triangular superior
    tamanho = length(b)
    x=zeros(tamanho,1)
    
    i = 1
    while (i <= tamanho)
        x[i] = b[i]/T[i,i]
        for j in 1:(i-1)
            x[i] -= T[i, j] * x[j]/T[i,i]
        end
        i += 1
    end
    return x
end

resolve_triangular_inferior (generic function with 1 method)

In [16]:
function eliminacao_gaussiana(A,b) #A é uma matriz cheia ("matriz densa")
    tamanho = length(b)
    for i in 1:tamanho-1
        for j in i+1:tamanho
            multiplicador = A[j,i]/A[i,i]
            A[j, :] = A[j, :] - multiplicador*A[i, :]
            b[j] = b[j] - multiplicador*b[i]
        end
    end
    return A,b
end

eliminacao_gaussiana (generic function with 1 method)

In [6]:
function resolve_cheia(A,b)
    T,c= eliminação_gaussiana(A,b)  #O(n^3)
    x=resolve_triangular_superior(T,b)  #O(n^2)
    return x
end

resolve_cheia (generic function with 1 method)

In [7]:
function decomposicao_LU(A) #A é uma matriz cheia ("matriz densa")
    tamanho = size(A)
    tamanho = tamanho[1]
    L=zeros(tamanho,tamanho)
    
    for i in 1:tamanho
        L[i,i] = 1
    end
    
    U = zeros(tamanho, tamanho)
    
    for i in 1:tamanho
        for j in 1:tamanho
            U[i, j] = A[i, j]
        end
    end
    
    for i in 1:tamanho-1
        for j in i+1:tamanho
            L[j,i] = U[j,i]/U[i,i]
            U[j, :] = U[j, :] -L[j,i]*U[i, :]
        end
    end

    return L,U 
end

decomposição_LU (generic function with 1 method)

In [8]:
function resolver_pos_LU(L,U,b)    #O(n^2) 
    y=resolve_triangular_inferior(L,b)
    x=resolve_triangular_superior(U,y)
    return x
end

resolver_pós_LU (generic function with 1 method)

## Testes das Funções

# Questão 2.

### Método de Taylor

In [139]:
""" Essa função faz a aproximação de uma função no ponto 'desejado' utilizando o polinômio de taylor
centrado no ponto 'referencia'. Para isso, deve-se passar a função, as múltiplas derivadas (quantas 
quiser - quanto mais melhor) e os pontos de referencia e desejado."""

function taylor(funcao, derivadas, referencia, desejado)  #TODO
    grau = length(derivadas)
    soma = funcao(referencia)
    fat = 1
    for i in 1:grau
        fat = fat * i
        soma = soma + (derivadas[i](referencia)*(desejado-referencia)^i)/fat
    end
    return soma
end

taylor (generic function with 1 method)

In [153]:
f(x) = log(x)
fd1(x) = 1/x; fd2(x) = -1/x^2; fd3(x) = 2/x^3; fd4(x) = -6/x^4; fd5(x) = 24/x^5; fd6(x) = -120/x^6; fd7(x) = 720/x^7;
der = [fd1,fd2,fd3,fd4,fd5,fd6,fd7]

println(taylor(f, der, 1, 1.5))
println(log(1.5))

0.40580357142857143
0.4054651081081644


In [149]:
f(x) = sin(x)
fd1(x) = cos(x); fd2(x) = -sin(x); fd3(x) = -cos(x); fd4(x) = sin(x); fd5(x) = cos(x); fd6(x) = -sin(x); fd7(x) = -cos(x);
der = [fd1,fd2,fd3,fd4,fd5,fd6,fd7]

println(taylor(f, der, 1, 1.3))
println(sin(1.2))

0.9635581840200099
0.9320390859672263


In [156]:
f(x) = x^5+4x^4-3x^2+1
fd1(x) = 5x^4+16x^3-6x; fd2(x) = 20x^3+48x^2-6; fd3(x) = 60x^2+96x; fd4(x) = 120x+96; fd5(x) = 120;
der = [fd1,fd2,fd3,fd4,fd5]

println(taylor(f, der, 1, 1.3))
println(f(1.3))

11.067330000000004
11.067330000000002


### Achar o Zero da Função

In [ ]:
function achar_zero_de_função(função, precisão) #intervalo?, derivadas?
    return solução
end

### Achar o Zero da Função por Bisseção

In [1]:
""" Na bisseção, queremos reduzir o intervalo ao máximo sempre garantindo que a função nos
extremos tenha sinais distintos, visto que isso garante, pelo Teorema do Valor Intermediário,
a existência de um zero de função nesse intervalo. Sendo assim, passamos a função, os extremos
esquerdo e direito do intervalo e o erro máximo esperado.
Retornamos a estimativa com um erro menor que o esperado."""

function bissecao(f, esq, dir, erro = 1e-2)
    m=0
    
    if f(esq)*f(dir)>0
        println("ERRO: O intervalo passado não possui extremos com sinais distintos. Não podemos garantir um zero da função!")
        return
    end
    
    while abs(dir-esq) > erro
        m = (esq+dir)/2
        res = f(m)
        
        if res == 0.0
            break
        elseif res*f(esq) > 0     # verifica se f(m) e f(esq) possuem o mesmo sinal
            esq = m
        else                      
            dir = m
        end
    end
    
    return m
end

bissecao (generic function with 2 methods)

In [2]:
f(x) = x^5+4x^4-3x^2+1
bissecao(f,-3,3)

ERRO: O intervalo passado não possui extremos com sinais distintos. Não podemos garantir um zero da função!


In [3]:
f(x) = x^5+4x^4-3x^2+1
bissecao(f,-10,10)

-3.798828125

In [4]:
f(x) = sin(x/2)
bissecao(f, 1, 10)

6.2822265625

### Achar o Zero da Função por Ponto Fixo

In [1]:
# Chris
function ponto_fixo(f, eps, x0)
    # Inicializa com infinito para saber se encontramos
    ponto_fixo = -Inf
    
    # quantidade de iterações dadas até encontrar
    steps = 1
    
    while true
        nx = f(x0)

        if abs(nx - x0) < eps
            # achamos uma aproximação que respeita a margem de erro 
            ponto_fixo = nx
            break
        end

        steps += 1
        x0 = nx
    end
    
    # método falhou
    @assert(ponto_fixo != -Inf, "Método falhou. Não achamos 
            uma aproximação com a margem de erro desejada")
    
    # retorna o ponto_fixo da função
    return ponto_fixo
end


ponto_fixo (generic function with 1 method)

In [2]:
function f(x)
    return x*cos(x) - x*x + 8*x - 1
end

function g(x)
    # g(x) é uma função cujo ponto fixo é um zero de f(x)
    return (x*cos(x) - x*x -1)/8.0
end

println(ponto_fixo(g, 0.001, 0.0))

-0.14558862306442932


### Achar o Zero da Função por Newton

In [193]:
""" Para o método de Newton, queremos nos aproveitar do ângulo tangente da curva para nos
aproximarmos precisamente do zero da função. Isso é feito encontrando a reta tangente a
curva no ponto atual e indo para o ponto dessa reta que cruza o eixo x. Para isso, precisamos
da função e sua derivada, o ponto inicial do método e o erro máximo esperado."""

function newton(f, fd, ponto, erro = 1e-8)
    # Primeiro descobrimos quantos termos precisamos
    termos = 1
    while (termos+1)*(2^(termos+1)) < 1/erro
        termos = termos+1
    end

    # Agora calculamos o taylor
    for i in 1:termos
        ponto = ponto - f(ponto)/fd(ponto)
    end
    
    return ponto
end

newton (generic function with 2 methods)

In [198]:
f(x) = x^5+4x^4-3x^2+1
fd(x) = 5x^4+16x^3-6x
newton(f,fd,-4)

-3.796694419165162

In [197]:
f(x) = sin(x/2)
fd(x) = 1/2 * cos(x/2)
newton(f, fd, 6)

6.283185307179586

In [200]:
f(x) = log(x)
fd(x) = 1/x
newton(f, fd, 2)

1.0

### Achar o Zero da Função pelo Método de Euler

In [ ]:
# Chris

# Método de Euler

### Resolver EDO com Problema de Valor Inicial

In [1]:
# Chris
function resolver_PVI(derivada, x_inicial,y_inicial,x_final,n) #Feito
    # tamanho do intervalo que usaremos dada a discretização desejada
    H = (x_final-x_inicial) / n
    
    # passos iniciais
    xi = x_inicial
    yi = y_inicial

    while xi + H <= x_final
        # pegamos o próximo valor de y andando pela reta tangente ao 
        # ponto x_i com um passo de tamanho H
        yi += derivada(xi, yi) * H
        xi += H
    end
    
    return yi # retornamos o valor de y no estado final
end

resolver_PVI (generic function with 1 method)

In [17]:
function df(x, y)
    return y
end

# queremos aproximar y(4) usando método de euler
# sendo y'(x) = y(x), y(0) = 1 e dividindo o intervalo em 40 partes

resolver_PVI(df, 0.0, 1.0, 4, 40)

41.144777789250874

In [23]:
function df(x, y)
    return y + 3*x
end

# queremos aproximar y(3) usando método de euler
# sendo y'(x) = y + 3x, y(3) = 1 e dividindo o intervalo em 3 partes

resolver_PVI(df, 0.0, 1.0, 3, 3)

20.0

In [26]:
function df(x, y)
    return exp(-x)
end

# queremos aproximar y(5) usando método de euler
# sendo y'(x) = x^2 + 3x, y(2) = 10 e dividindo o intervalo em 40 partes

resolver_PVI(df, 0.0, 0.0, 2, 4)

1.0987701305162527

### Resolver EDO com Problema de Valor de Contorno

In [ ]:
# Luan
function resolver_PVC(segunda_derivada(x,y), x_inicial, y_inicial, x_final, y_final,n)  #Não dá pra fazer genericamente
    A,b=#usuário monta um sistema linear usando diferenças finitas(segunda_derivada(x,y), x_inicial, y_inicial, x_final, y_final,n)
    y = resolver_um_sistema(A,b)
    return y

### Resolver um Sistema Ax=b

In [9]:
""" Essa função é um encapsulamento da resolução de sistema do formato 'A.x = b' 
utilizando decomposição LU. Para isso, é passado como parâmetro a matriz A e o 
vetor b, e o resultado será o vetor x."""

function resolver_um_sistema(A,b) 
    L, U = decomposição_LU(A)
    x = resolver_pós_LU(L,U,b)
    return x
end

resolver_um_sistema

In [31]:
A=[1.0 3.0 2.0 7.0 ; 10.0 3.0 10.0 7.0 ; 3.0 5.0 18.0 22.0 ; 5.0 2.0 1.0 6.0]
b=[9.0 ; 23.0 ; 45.0 ; 20.0]

println(resolver_um_sistema(A,b))
println(A\b)

[2.1040532365396274; -5.474289171203875; -0.6170598911070786; 3.5075620084694505]
[2.104053236539625, -5.474289171203873, -0.6170598911070775, 3.507562008469449]


In [201]:
A=[1.0 3.0 2.0 ; -2.0 -1.0 5.0 ; 1.0 1.0 1.0]
b=[9.0 ; 3.0 ; -3.0]

println(resolver_um_sistema(A,b))
println(A\b)

[-8.307692307692305; 6.692307692307692; -1.3846153846153844]
[-8.307692307692307, 6.692307692307692, -1.3846153846153846]


In [205]:
A=[1.0 3.0 ; -1.0 2.0]
b=[3.0 ; -2.0]

println(resolver_um_sistema(A,b))
println(A\b)

[2.4; 0.2]
[2.4, 0.2]


### Gerar a Matriz de Vandermonde

In [46]:
""" Essa função recebe uma lista de pontos x e retorna uma matriz cujas colunas são 
dadas por essa lista de pontos elevado a uma potência. A primeira coluna possui apenas 1s, 
a segunda é potência de 1, a terceira de 2, e assim em diante até o grau especificado. """

function matriz_de_vandermonde(pontos_x, grau)
    matriz = ones(length(pontos_x))
    for i in 1:grau
        matriz = hcat(matriz, pontos_x.^i)
    end 
    return matriz
end

matriz_de_vandermonde (generic function with 1 method)

In [47]:
matriz_de_vandermonde([1,2,4,2,-1], 3)

5×4 Array{Float64,2}:
 1.0   1.0   1.0   1.0
 1.0   2.0   4.0   8.0
 1.0   4.0  16.0  64.0
 1.0   2.0   4.0   8.0
 1.0  -1.0   1.0  -1.0

In [206]:
matriz_de_vandermonde([1,-1,2,3,-5], 1)

5×2 Array{Float64,2}:
 1.0   1.0
 1.0  -1.0
 1.0   2.0
 1.0   3.0
 1.0  -5.0

In [208]:
matriz_de_vandermonde([2,3,1,2], 5)

4×6 Array{Float64,2}:
 1.0  2.0  4.0   8.0  16.0   32.0
 1.0  3.0  9.0  27.0  81.0  243.0
 1.0  1.0  1.0   1.0   1.0    1.0
 1.0  2.0  4.0   8.0  16.0   32.0

### Fazer Interpolação de Curva por Vandermonde

In [220]:
""" Nessa função, realizamos o processo de interpolação de curvas utilizando a matriz de 
Vandermonde para o sistema. Consiste em passarmos os pontos de x e y como duas listas 
separadas e o grau do polinômio, e a função retorna os coeficientes
do polinômio, na ordem do grau 0 até o grau especificado."""

function interpolacao_coeficientes(pontos_x, pontos_y, grau)
    V = matriz_de_vandermonde(pontos_x,grau)
    coeficientes = resolver_um_sistema(V,pontos_y)
    return coeficientes
end

interpolacao_coeficientes (generic function with 1 method)

In [221]:
interpolacao_coeficientes([1,5,6,9], [3,2,4,4], 3)

4×1 Array{Float64,2}:
  9.062500000000002
 -7.818750000000001
  1.8750000000000002
 -0.11875000000000001

In [222]:
interpolacao_coeficientes([-1,0,1.87,1,-2,2], [-2.0,-3.0,0,-10,-36.72,6.7], 5)

6×1 Array{Float64,2}:
 -3.0
 -5.303660976593872
 -2.9991666666666665
  0.3916595540756744
 -0.0008333333333331722
  0.9120014225181984

In [223]:
interpolacao_coeficientes([0,1,-1,2], [3,8,-2,13], 3)

4×1 Array{Float64,2}:
 3.0
 5.0
 0.0
 0.0

### Obter Polinômio por Lagrange

In [3]:
# Chris
using Polynomials

function lagrange(pontos_x, pontos_y, grau)
    
    poly = Polynomial(0.0)

    for i in 1 : grau
        coeff = Polynomial(pontos_y[i])
        for j in 1 : grau
            if i == j
                # caso especial, não consideramos os
                # mesmos índices
                continue
            end

            # adicionamento esse coeficiente no polinômio
            coeff = coeff * Polynomial([-pontos_x[j], 1.0]) / (pontos_x[i] - pontos_x[j])
        end

        # adicionamos o coeficiente no polinômio
        poly += coeff
    end

    # retornamos polinômio na forma [1, x, x^2, ..., x^(grau-1)]
    return poly
end

lagrange (generic function with 1 method)

In [5]:
x = [1.0, 2.0, 7.0]
y = [2.0, 5.0, 9.0]

println(coeffs(lagrange(x, y, 3)))

[-1.733333333333333, 4.1, -0.36666666666666675]


In [6]:
x = [-1.0, 2.0, 3.0, 5.0]
y = [0.0, 1.0, 1.0, 2.0]

println(coeffs(lagrange(x, y, 3)))

[0.5, 0.41666666666666674, -0.08333333333333331]


In [7]:
x = [0.0, 2.0, 4.0]
y = [-2.0, 1.0, 4.0]

println(coeffs(lagrange(x, y, 2)))

[-2.0, 1.5]


### Fazer Interpolação de Curva por Lagrange

In [ ]:
# Vinicius

function interpolacao_funcao(pontos_x,pontos_y, grau)
    polinomio =lagrange(pontos_x,pontos_y,grau)
    return polinomio
end

### Aplicação de um x em uma função

In [ ]:
# Thierry
function aplica(coeficientes, valor_de_x) #Hashi
    return valor_do_polinômio_no_x
end

### Regressão Linear de Funções Lineares

In [ ]:
# Thierry
function regressão_coeficientes_lineares(pontos_x,pontos_y, grau) #Feito
    V=matrix_de_vandermonde(pontos_x,grau)  #matrix alta #muitas linhas e poucas colunas 
    coeficientes=resolver_um_sistema_por_minimos_quadrados(V,pontos_y)
    return coeficientes
end

### Regressão Linear de Funções Exponenciais

In [ ]:
# Thierry
function regressão_função_exponencial(pontos_x,pontos_y, grau) #coeficientes não lineares
    #dicionário ("linearização") é feito manualmente ou por uma tabela
    pontos_y_barra=ln(pontos_y)
    pontos_x_barra=x
    
    #resolver regresssão com coeficientes lineares no "mundo barra"
    regressão_coeficientes_lineares(pontos_x_barra,pontos_y_barra, grau)
    
    #voltar para o mundo original
    coeficientes=e^(coeficientes_barra)
    
    return coeficientes
end

### Perguntar

In [ ]:
# Perguntar pra ele
function regresso_função_outra_funçao(pontos_x,pontos_y, grau) #coeficientes não lineares
    #dicionário ("linearização") é feito manualmente ou por uma tabela
    ??????????????
    
    #resolver regresssão com coeficientes lineares no "mundo barra"
    regressão_coeficientes_lineares(pontos_x_barra,pontos_y_barra, grau)
    
    #voltar para o mundo original
    ???????????????????????
    
    return coeficientes
end

### Resolver um Sistema por Mínimos Quadrados

In [ ]:
# Thierry
function resolver_um_sistema_por_minimos_quadrados(A,b) #feito
    x=resolver_um_sistema(A'*A,A'*b)
    return x
end

### Integração pela Regra do Retângulo

In [55]:
""" O objetivo dessa função é aproximar a integração da função no intervalo [a,b] utilizando 
o somatório de n retângulos dados pela base sendo o intervalo [x_k,x_k+1] e a altura como a 
média das funções nesses dois pontos. O retorno será a estimativa da integral."""

function regra_do_retangulo(funcao,a,b,n)
    integral = 0.0
    h = (b-a)/n 
    for i in 1:n
        f = (funcao( a+h*i ) + funcao( a+h*(i-1) ))/2
        integral = integral + f*h
    end
    return integral
end

regra_do_retangulo

In [56]:
f(x) = 2x^2-x
regra_do_retangulo(f,0,5,100)

70.83750000000002

In [228]:
f(x) = log(x)
regra_do_retangulo(f,1,5,100)

4.047082902554811

In [234]:
f(x) = sin(x)
regra_do_retangulo(f,-10,10,100)

-1.0834161259104524e-15

### Integração pela Regra do Trapézio

In [57]:
""" O objetivo dessa função é aproximar a integração da função no intervalo [a,b] utilizando o 
somatório de n trapézios dados pelo intervalo [x_k,x_k+1] e as duas bases como as funções nesses 
dois pontos. O retorno será a estimativa da integral."""

function regra_do_trapezio(funcao,a,b,n)
    soma = f(a)+f(b)
    for i = 1:n-1
        x = a + i*(b-a)/n
        soma = soma + 2*f(x)
    end
    
    return soma * (b-a) / (2*n)
end

regra_do_trapezio (generic function with 1 method)

In [61]:
f(x) = 2x^2-x
regra_do_trapezio(f,0,5,100)

70.8375

In [235]:
f(x) = log(x)
regra_do_trapezio(f,1,5,100)

4.047082902554812

In [236]:
f(x) = sin(x)
regra_do_trapezio(f,-10,10,100)

1.7763568394002506e-16

### Integração pela Regra do Simpson

In [8]:
function regra_de_simpson(f, a, b, n)
    @assert(n % 2 == 0, "você precisa escolher um n par!")
    # regra de simpson composta, consiste
    h = (b - a) / n / 2.0

    # adicionamos de antemão a contribuição dos
    # pontos nas extremidades
    S = f(a) + f(b)

    # vamos somar agora a imagem dos pontos médios
    for i in 1 : (n << 1)-1
        if (i & 1 == 1)
            # termo ímpar tem peso 4
            S += f(a + h * i) * 4
        else 
            # termo par tem peso 2
            S += f(a + h * i) * 2
        end
    end

    return S / 3.0 * h
end

regra_de_simpson (generic function with 1 method)

In [9]:
function f(x)
    return x*x - 16*x - exp(x)
end

println(regra_de_simpson(f, 1.0, 4.0, 48))

-150.87986847952268


In [15]:
function f(x) 
    return exp(-x^2)
end

# nesse caso temos uma integral sem uma primitiva analítica
println(regra_de_simpson(f, 0.0, 2.0, 2112));

0.8820813907624211


In [14]:
function f(x) 
    return exp(-x^2)
end

println(regra_de_simpson(f, 0.0, acos(-1.0)/2.0, 5322))

0.8629004801502503


### Obter o Máximo de uma Função

In [ ]:
# Perguntar pra ele
function maximar_uma_funcao(função,derivada) #muito difícil!!!!!!!
    return max_global
end

### Encontrar um ponto crítico de uma função

In [ ]:
# Luan
function achar_um_ponto_critico_de_uma_funcao(derivada_da_função(x),intervalo) #feito
    ponto_crítico=bisseção(derivada(x),intervalo) #ou newton ou ponto fixo...
    return ponto_crítico
end

### Encontrar um ponto crítico de uma função de 2 variáveis

In [107]:
""" Nessa função, queremos encontrar um ponto crítico em uma função de duas variáveis. Para isso, utilizamos o 
método do gradiente descendente, em que descemos a curva da função através do decremento do gradiente, visto que
este aponta para a direção de maior crescimento. Para isso, é necessário passar o gradiente da função no formato 
[fdx, fdy], os intervalos de x e y no formato [a, b] e a quantidade de iterações a ser realizada pelo método. """

function achar_um_ponto_critico_de_uma_funcao_de_2_variaveis(gradiente_da_funcao, intervalox, intervaloy, iteracoes)
    # Iniciamos aleatoriamente o ponto
    px = rand(intervalox[1]:intervalox[2])
    py = rand(intervaloy[1]:intervaloy[2])
    taxa = 0.1
    
    for i in 1:iteracoes
        # Obtemos o gradiente no ponto
        grad = gradiente_da_funcao(px,py)
        
        # Checamos se esta dentro do intervalo pedido para descer o gradiente
        if (intervalox[1]<=px-grad[1]*taxa<=intervalox[2]) && (intervaloy[1]<=py-grad[2]*taxa<=intervaloy[2])
            px = px - grad[1]*taxa
            py = py - grad[2]*taxa
        else
            break       # Senão acabamos a iteracao
        end 
    end
    
    return [px,py]
end

achar_um_ponto_critico_de_uma_funcao_de_2_variaveis (generic function with 1 method)

In [108]:
# Testando a função x^2+2y^2-3x

d(x,y) = [2x-3, 4y]
achar_um_ponto_critico_de_uma_funcao_de_2_variaveis(d, [-10,10], [-10,10], 500)

2-element Array{Float64,1}:
 1.5000000000000004
 2.3804287532992367e-111

In [281]:
# A função x^4 + x*y^3 - 2x^2*y + x - 5yx tem mínimo local em (-0.769, -1.074)

d(x,y) = [4x^3+y^3-4y*x+1-5y,-2x^2+3x*y^2-5x]
achar_um_ponto_critico_de_uma_funcao_de_2_variaveis(d, [-5,5], [-5,5], 500)

2-element Array{Float64,1}:
 -0.7697453971177661
 -1.074012601689643

In [292]:
# Função sen(x)*cos(y/5) possui muitos pontos locais de minimo e maximo

d(x,y) = [cos(y/5)*cos(x), -1/5*sin(x)*sin(y/5)]
achar_um_ponto_critico_de_uma_funcao_de_2_variaveis(d, [-5,5], [-5,5], 500)

2-element Array{Float64,1}:
 -1.5707963267948957
 -0.30667690649675944

### Obter Lagrange em 2D

In [ ]:
# Thierry
function langrage_2D()
    
end