# <center> Cálculo numérico 2020.2: Tarefa 7 </center>

<h3> Aluno: Thierry Pierre Dutoit <br>DRE: 119040432 </h3>

## Exercício 1 

Generalize os códigos das funções abaixo que fizemos na aula 15 para matrizes n × n (não precisa se preocupar com divisões por zero nem com troca de linhas ou colunas).


(a) RESOLVE_DIAGONAL

In [14]:
using LinearAlgebra
function resolve_diagonal(D,b) #D é diagonal
    tamanho = length(b)
    x=zeros(tamanho,1)
    for i in 1:tamanho
        x[i] = b[i]/D[i,i]
    end
    return x
end

resolve_diagonal (generic function with 1 method)

In [15]:
D=[2 0 0;0 4 0;0 0 194]
b=randn(3,1)
x=resolve_diagonal(D,b)
norm(D*x-b)

0.0

In [34]:
function resolve_triangular_superior(T,b) #T é triangular superior
    tamanho = length(b)
    x=zeros(tamanho,1)
    
    i = tamanho
    while (i > 0)
        x[i] = b[i]/T[i,i]
        k = tamanho
        for j in i:(tamanho - 1)
            x[i] -= T[i, k] * x[k]/T[i,i]
            k -= 1
        end
        i -= 1
    end
    return x
end

resolve_triangular_superior (generic function with 1 method)

In [38]:
T=[1 2 3;0 2 3;0 0 1]
b=randn(3,1)
x=resolve_triangular_superior(T,b)
println(abs(norm(T\b - x)))
norm(T*x-b)

0.0


0.0

In [46]:
T=[5 6 0;0 7 2;0 0 8]
b=randn(3,1)
x=resolve_triangular_superior(T,b)
println(abs(norm(T\b - x)))
norm(T*x-b)

0.0


0.0

In [47]:
function resolve_triangular_inferior(T,b) #T é triangular superior
    tamanho = length(b)
    x=zeros(tamanho,1)
    
    i = 1
    while (i <= tamanho)
        x[i] = b[i]/T[i,i]
        for j in 1:(i-1)
            x[i] -= T[i, j] * x[j]/T[i,i]
        end
        i += 1
    end
    return x
end

resolve_triangular_inferior (generic function with 1 method)

In [50]:
T=[7 0 0;2 7 0;8 4 6]
b=randn(3,1)
x=resolve_triangular_inferior(T,b)
println(abs(norm(T\b - x)))
norm(T*x-b)

0.0


0.0

In [51]:
function eliminação_gaussiana(A,b) #A é uma matriz cheia ("matriz densa")
    tamanho = length(b)
    for i in 1:tamanho-1
        for j in i+1:tamanho
            multiplicador = A[j,i]/A[i,i]
            A[j, :] = A[j, :] - multiplicador*A[i, :]
            b[j] = b[j] - multiplicador*b[i]
        end
    end
    return A,b
end

eliminação_gaussiana (generic function with 1 method)

In [52]:
A=[2 4 3;4 10 9;6 18 22]
b=[9; 23; 46]
eliminação_gaussiana(A,b)

([2 4 3; 0 2 3; 0 0 4], [9, 5, 4])

In [54]:
function resolve_cheia(A,b)
    T,c= eliminação_gaussiana(A,b)  #O(n^3)
    x=resolve_triangular_superior(T,b)  #O(n^2)
    return x
end

resolve_cheia (generic function with 1 method)

In [55]:
x=resolve_cheia(A,b)
A*x-b

3×1 Matrix{Float64}:
 0.0
 0.0
 0.0

In [104]:
function decomposição_LU(A) #A é uma matriz cheia ("matriz densa")
    tamanho = size(A)
    tamanho = tamanho[1]
    L=zeros(tamanho,tamanho)
    
    for i in 1:tamanho
        L[i,i] = 1
    end
    
    U = zeros(tamanho, tamanho)
    
    for i in 1:tamanho
        for j in 1:tamanho
            U[i, j] = A[i, j]
        end
    end
    
    for i in 1:tamanho-1
        for j in i+1:tamanho
            L[j,i] = U[j,i]/U[i,i]
            U[j, :] = U[j, :] -L[j,i]*U[i, :]
        end
    end

    return L,U 
    
end

decomposição_LU (generic function with 1 method)

In [121]:
A=randn(3,3)

3×3 Matrix{Float64}:
 -0.993892  -0.934912  -0.239401
  0.271955   0.666668   1.22339
 -0.766278  -0.545153   1.67974

In [122]:
L,U=decomposição_LU(A)

([1.0 0.0 0.0; -0.27362628536650696 1.0 0.0; 0.7709874074215826 0.4275329244527357 1.0], [-0.9938920965501371 -0.9349124184780709 -0.23940089306901546; 0.0 0.4108518715222914 1.1578828980730274; 0.0 0.0 1.3692782251545652])

In [123]:
A-L*U

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [124]:
function resolver_pós_LU(L,U,b)    #O(n^2) 
    y=resolve_triangular_inferior(L,b)
    x=resolve_triangular_superior(U,y)
    return x
end

resolver_pós_LU (generic function with 1 method)